apiVersion: batch/v1
kind: Job

metadata:
  name: job-carla-0
  namespace: carla

spec:
  parallelism: 1    # 并行运行的 Pod 数量
  completions: 10   # 总共需要运行的 Pod 数量
  template:    
    spec:
      containers:
      - name: c-carla-api
        image: dxlcq/scene
        command: ["python", "generator.py", "180.85.207.42", "32000", "scene1.json", "/mnt/nfs/job-0"] # 修改启动命令
        volumeMounts:
          - name: v-nfs
            mountPath: /mnt/nfs
        env:
          - name: TZ
            value: Asia/Shanghai

      restartPolicy: Never

      volumes:
        - name: v-nfs
          persistentVolumeClaim:
            claimName: pvc-nfs

---

apiVersion: batch/v1
kind: Job

metadata:
  name: job-carla-2
  namespace: carla

spec:
  parallelism: 1    # 并行运行的 Pod 数量
  completions: 10   # 总共需要运行的 Pod 数量
  template:    
    spec:
      containers:
      - name: c-carla-api
        image: dxlcq/scene
        command: ["python", "generator.py", "180.85.207.42", "32002", "scene1.json", "/mnt/nfs/job-2"] # 修改启动命令
        volumeMounts:
          - name: v-nfs
            mountPath: /mnt/nfs
        env:
          - name: TZ
            value: Asia/Shanghai

      restartPolicy: Never

      volumes:
        - name: v-nfs
          persistentVolumeClaim:
            claimName: pvc-nfs

---

apiVersion: batch/v1
kind: Job

metadata:
  name: job-carla-4
  namespace: carla

spec:
  parallelism: 1    # 并行运行的 Pod 数量
  completions: 10   # 总共需要运行的 Pod 数量
  template:    
    spec:
      containers:
      - name: c-carla-api
        image: dxlcq/scene
        command: ["python", "generator.py", "180.85.207.42", "32004", "scene1.json", "/mnt/nfs/job-4"] # 修改启动命令
        volumeMounts:
          - name: v-nfs
            mountPath: /mnt/nfs
        env:
          - name: TZ
            value: Asia/Shanghai

      restartPolicy: Never

      volumes:
        - name: v-nfs
          persistentVolumeClaim:
            claimName: pvc-nfs

---

apiVersion: batch/v1
kind: Job

metadata:
  name: job-carla-6
  namespace: carla

spec:
  parallelism: 1    # 并行运行的 Pod 数量
  completions: 10   # 总共需要运行的 Pod 数量
  template:    
    spec:
      containers:
      - name: c-carla-api
        image: dxlcq/scene
        command: ["python", "generator.py", "180.85.207.42", "32006", "scene1.json", "/mnt/nfs/job-6"] # 修改启动命令
        volumeMounts:
          - name: v-nfs
            mountPath: /mnt/nfs
        env:
          - name: TZ
            value: Asia/Shanghai

      restartPolicy: Never

      volumes:
        - name: v-nfs
          persistentVolumeClaim:
            claimName: pvc-nfs

---

apiVersion: batch/v1
kind: Job

metadata:
  name: job-carla-8
  namespace: carla

spec:
  parallelism: 1    # 并行运行的 Pod 数量
  completions: 10   # 总共需要运行的 Pod 数量
  template:    
    spec:
      containers:
      - name: c-carla-api
        image: dxlcq/scene
        command: ["python", "generator.py", "180.85.207.42", "32008", "scene1.json", "/mnt/nfs/job-8"] # 修改启动命令
        volumeMounts:
          - name: v-nfs
            mountPath: /mnt/nfs
        env:
          - name: TZ
            value: Asia/Shanghai

      restartPolicy: Never

      volumes:
        - name: v-nfs
          persistentVolumeClaim:
            claimName: pvc-nfs
