apiVersion: batch/v1
kind: Job

metadata:
  name: job-carla-3
  namespace: carla

spec:
  parallelism: 3    # 并行运行的 Pod 数量
  completions: 10   # 总共需要运行的 Pod 数量
  template:
    metadata:
      labels:
        only: one 
    
    spec:
      hostNetwork: true # 使用宿主机网络

      affinity:
        
        nodeAffinity:                                     # 节点亲和
          requiredDuringSchedulingIgnoredDuringExecution: # 硬亲和
            nodeSelectorTerms:
            - matchExpressions:
              - key: kubernetes.io/hostname
                operator: In    # 节点中存在 key:value
                values:
                - k8s1          # 只允许调度到 GPU 节点
                - k8s2
                - k8s3
        
        podAntiAffinity:                                  # pod 反亲和
          requiredDuringSchedulingIgnoredDuringExecution: # 硬亲和
          - labelSelector:
              matchExpressions:
              - key: only
                operator: In    # 节点中存在 key:value
                values:
                - one           # 防止同一个节点上运行多个 Pod
            topologyKey: "kubernetes.io/hostname"
      
      containers:
      - name: c-carla-api
        image: dxlcq/scene
        command: ["python", "generator.py", "127.0.0.1", "2000", "scene3.json", "/mnt/nfs/job-3"] # 修改启动命令
        volumeMounts:
          - name: v-nfs
            mountPath: /mnt/nfs
        env:
          - name: TZ
            value: Asia/Shanghai

      restartPolicy: Never

      volumes:
        - name: v-nfs
          persistentVolumeClaim:
            claimName: pvc-nfs