apiVersion: v1
kind: Service

metadata:
  name: service-carla
  namespace: carla-base

spec:
  selector:
    app: carla

  ports:
    - name: carla2000
      protocol: TCP
      port: 32000
      targetPort: 32000
      nodePort: 32000
    - name: carla2001
      protocol: TCP
      port: 32001
      targetPort: 32001
      nodePort: 32001
  type: NodePort