apiVersion: v1
kind: Pod

metadata:
  name: ubuntu

spec:
  containers:
    - name: ubuntu
      image: ubuntu:latest
      command: ["sleep","infinity"]
      volumeMounts:
        - name: nfs
          mountPath: /mnt/nfs  # 挂载路径

  volumes:
    - name: nfs
      persistentVolumeClaim:
        claimName: nfs.pvc  # 引用 PVC 名称
