apiVersion: apps/v1
kind: Deployment
metadata:
  name: gpu-test
  namespace: carla-base
spec:
  replicas: 3
  selector:
    matchLabels:
      app: gpu-test
  template:
    metadata:
      labels:
        app: gpu-test
    spec:
      schedulerName: ymca-scheduler  # 关键参数
      containers:
      - name: nginx
        image: nginx:alpine