# ymca-scheduler-crb.yaml
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: ymca-scheduler-crb
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: ymca-scheduler-cr
subjects:
- kind: ServiceAccount
  name: ymca-scheduler-sa
  namespace: carla